### ISSUE TITLE
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"

### ISSUE THREAD

**Issue by Normal-1310** [brblacky/WaveMusic#18]
```
MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
    at new ConnectionString (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongodb-connection-string-url\lib\index.js:86:19)
    at parseOptions (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongodb\lib\connection_string.js:217:17)
    at new MongoClient (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongodb\lib\mongo_client.js:62:63)
    at C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\connection.js:784:16
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\connection.js:781:19)
    at C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\index.js:340:10
    at C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10) Promise {
  <rejected> MongoParseError: Invalid scheme, expected connection string to start with "mongodb://" or "mongodb+srv://"
      at new ConnectionString (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongodb-connection-string-url\lib\index.js:86:19)
      at parseOptions (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongodb\lib\connection_string.js:217:17)
      at new MongoClient (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongodb\lib\mongo_client.js:62:63)
      at C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\connection.js:784:16
      at new Promise (<anonymous>)
      at NativeConnection.Connection.openUri (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\connection.js:781:19)
      at C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\index.js:340:10
      at C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:32:5
      at new Promise (<anonymous>)
      at promiseOrCallback (C:\Users\Nopparat\Desktop\Nop\WaveMusic-main\node_modules\mongoose\lib\helpers\promiseOrCallback.js:31:10)
```

**Comment by LucasB25** [comment]
Your basic data link you put and inccorect

Show the basic data link you put, and hide the passwords

**Comment by Normal-1310** [comment]
mongodb://Makarm:********@cluster0.fgj2lth.mongodb.net/?retryWrites=true&w=majority

**Comment by Normal-1310** [comment]
> mongodb+srv://[username mongo]:[pass mongo]@cluster0.cij65.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

not work

**Comment by brblacky** [comment]
Check your Mongodb is is not problem in code

**Comment by Normal-1310** [comment]
> 

do not have anything
