### ISSUE TITLE
skip slash command 

### ISSUE THREAD

**Issue by wsael** [brblacky/WaveMusic#54]
reject Promise {
  <rejected> AbortError: The user aborted a request.
      at abort (/home/container/node_modules/node-fetch/lib/index.js:1462:16)
      at EventTarget.abortAndFinalize (/home/container/node_modules/node-fetch/lib/index.js:1477:4)
      at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
      at EventTarget.dispatchEvent (node:internal/event_target:692:26)
      at abortSignal (node:internal/abort_controller:369:10)
      at AbortController.abort (node:internal/abort_controller:403:5)
      at Timeout.<anonymous> (/home/container/node_modules/discord.js/src/rest/APIRequest.js:72:49)
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7) {
    type: 'aborted'
  }
} FetchError: request to https://discord.com/api/v9/channels/1147599023277084815/messages/1147599025730748507 failed, reason: socket hang up
    at ClientRequest.<anonymous> (/home/container/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:529:35)
    at TLSSocket.socketCloseListener (node:_http_client:474:11)
    at TLSSocket.emit (node:events:529:35)
    at node:net:350:12
    at TCP.done (node:_tls_wrap:614:7) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
(node:128) [DEP0160] DeprecationWarning: The multipleResolves event has been deprecated.
HTTPError [AbortError]: The user aborted a request.
    at RequestHandler.execute (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:201:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (/home/container/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async MessageManager.edit (/home/container/node_modules/discord.js/src/managers/MessageManager.js:132:15)
    at async Object.run (/home/container/events/Players/playerDestroy.js:47:9) {
  code: 500,
  method: 'patch',
  path: '/channels/1147599023277084815/messages/1147599025730748507',
  requestData: {
    json: {
      content: '__**Join a voice channel and queue songs by name/url**__\n\n',
      tts: false,
      nonce: undefined,
      embeds: [Array],
      components: [Array],
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: [Object],
      flags: 0,
      message_reference: undefined,
      attachments: [Array],
      sticker_ids: undefined,
      thread_name: undefined
    },
    files: [ [Object] ]
  }

**Comment by BallavaNarayan** [comment]
your server where is bot is hosted has a poor internet connection that's why you receiving this error
