### ISSUE TITLE
[CLIENT] An error has occurred : Error [TokenMissing]: Request to use token, but token was unavailable to the client.

### ISSUE THREAD

**Issue by alexsandrejr** [brblacky/WaveMusic#75]
[10/25/2024] [5:33:03 PM] [index.js] [WaveMusic] › ✖  error     [CLIENT] An error has occurred : Error [TokenMissing]: Request to use token, but token was unavailable to the client.
    at fetchRecommendedShardCount (/home/ubuntu/WaveMusic/node_modules/discord.js/src/util/Util.js:69:21)
    at ShardingManager.spawn (/home/ubuntu/WaveMusic/node_modules/discord.js/src/sharding/ShardingManager.js:195:22)
    at Object.<anonymous> (/home/ubuntu/WaveMusic/src/index.js:28:6)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'TokenMissing'
}
![Screenshot_2](https://github.com/user-attachments/assets/28692583-2ea4-4053-a287-cb51da91e242)
![Screenshot_1](https://github.com/user-attachments/assets/594ca5ce-7852-4ba8-9b06-bd8d6c00367b)

Does anyone know why this is happening?

**Comment by ShadowGaming100** [comment]
fill the following file
.env.example 
then rename to .env
